num_epochs: 10000
batch_size: 128
learning_rate: 0.0001
input_dim: 30
num_classes: 21
dim_feedforward: 512
nhead: 3
num_layers: 2
dropout: 0.2
train_data_path: 'T3Data1best.mat'
val_data_path: 'T3Data2best.mat'
resume: null
